### PR TITLE
Fix crash when starting playback from a playlist with only a single item, fixes #13

### LINKED ISSUE #13: Crash when starting playback from a playlist with only a single item
The MediaRouterPlayService crashes when the playlist contains only a single item and the playback is started:

```
FATAL EXCEPTION: main
Process: com.github.nutomic.controldlna, PID: 24026
java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
       at java.util.ArrayList.get(ArrayList.java:413)
       at com.github.nutomic.controldlna.mediarouter.MediaRouterPlayService.resume(MediaRouterPlayService.java:338)
       at com.github.nutomic.controldlna.gui.RouteFragment.onClick(RouteFragment.java:486)
       at android.view.View.performClick(View.java:5612)
       at android.view.View$PerformClick.run(View.java:22288)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

### PR DESCRIPTION
**Pull request by matgoebl**
Fix crash when starting playback from a playlist with only a single item, fixes #13
Replaces #14 (forgot cherry pick branch there)

### CODE REVIEW

File: src/main/java/com/github/nutomic/controldlna/mediarouter/MediaRouterPlayService.java [hunk 1]
```diff
@@ -335,8 +335,10 @@ public void resume() {
 		intent.putExtra(MediaControlIntent.EXTRA_SESSION_ID, mSessionId);
 		mMediaRouter.getSelectedRoute().sendControlRequest(intent, null);
 		mPollingStatus = true;
-		new CreateNotificationTask().execute(mPlaylist.get(mCurrentTrack)
-				.getFirstPropertyValue(DIDLObject.Property.UPNP.ALBUM_ART_URI.class));
+		if (mCurrentTrack >= 0 && mCurrentTrack < mPlaylist.size()) {
```
Comment (aabaker) [inline src/main/java/com/github/nutomic/controldlna/mediarouter/MediaRouterPlayService.java]: does 
```
if (mCurrentTrack < 0 || mCurrentTrack >= mPlaylist.size()) {
    mCurrentTrack = 0;
}
```
work better here? It seems logical that if you have never played a track (i.e. mCurrentTrack = -1) it should start by playing track 1, if mCurrentTrack is > the playlist length you could play either the last or the first track but not playing anything seems wrong.

**Comment by matgoebl** [comment]
I changed the fix as you suggested.
The crash happens, when you start up with an empty playlist, long-click on any song and choose "add single item to playlist". 
With both fixes it does not start playing. You have to click once on the song when its in the playlist to start playing.
Nevertheless, its more important to fix the more annoying crash.

**Comment by aabaker** [comment]
I wasn't happy with a solution where there was a button with a play symbol active that did nothing when pressed, calling play() if the current track isn't valid seems like a safe alternative.
